<h1 id="Metode-NumerikPendahuluan-Analisis-Error-" style="text-align: center;"><strong>Metode Numerik</strong><br /><strong><span style="color: blue;">EigenValue dan EigenVektor Numerik</span></strong><br /><img style="" src="images/MetNum.png" alt="" /></h1>
<h2 id="(C)-Taufik-Sutanto---2019" style="text-align: center;">(C) Taufik Sutanto - 2020</h2>
<h2 id="tau-data-Indonesia-~-https://tau-data.id" style="text-align: center;">tau-data Indonesia ~ <a href="https://tau-data.id" target="_blank"><span style="color: #0009ff;">https://tau-data.id/mfds-nm-05/</span></a></h2>

# Eigenvalue (Eigenvector) Numerik:

* Pendahuluan Eigenvalue dan eigen vektor
* Aplikasi & Intuisi
* Karakteristik Polinomial
* Power Method
* Rayleigh Quotient
* Deflated Matrix Method
* Jacobi Method

<p><img alt="" src="images/intro_eigen.png" style="width: 800px; height: 404px;" /></p>


<p><img alt="" src="images/eigen_apps.png" style="width: 800px; height: 382px;" /></p>


<p><img alt="" src="images/eigen_intuition.png" style="width: 800px; height: 316px;" /></p>


# Karektiristik Polynomial ~ Permasalahan Mencari Akar

<p><img alt="" src="images/eigen_characteristic_polymoial.png" style="width: 800px; height: 481px;" /></p>


<h1 id="Keterbatasan">Keterbatasan - Companion Matrix</h1>

<p><img alt="" src="images/eigen_companion_matrix.png" style="width: 800px; height: 544px;" /></p>


# Contoh lain permasalahan numerik menggunakan AKP

<p><img alt="" src="images/eigen_numeric_problem.png" style="width: 800px; height: 518px;" /></p>


In [1]:
# Python implementation
import numpy as np

A = np.array([[ 1, 1 ],
              [ 0, 2 ]])
A

array([[1, 1],
       [0, 2]])

In [2]:
# Operasi Matrix
print('A \n',A)
print('A*A \n',A.dot(A))
print('A+A \n',A+A)
print("A' \n",A.transpose())

A 
 [[1 1]
 [0 2]]
A*A 
 [[1 3]
 [0 4]]
A+A 
 [[2 2]
 [0 4]]
A' 
 [[1 0]
 [1 2]]


In [3]:
# Eigenvalue dan eigenvector

A = np.array([[ 3, -1 ],[ -1, 3 ]])
print(A)
eVa, eVe = np.linalg.eig(A)
print('Eigenvalues \n',eVa)
print('Eigenvectors \n',eVe)

[[ 3 -1]
 [-1  3]]
Eigenvalues 
 [4. 2.]
Eigenvectors 
 [[ 0.70710678  0.70710678]
 [-0.70710678  0.70710678]]


In [4]:
A = [[1,2,3],[0,4,5],[0,0,6]]
A = np.array(A)
eVa, eVe = np.linalg.eig(A)
print('Eigenvalues \n',eVa)
print('Eigenvectors \n',eVe)

Eigenvalues 
 [1. 4. 6.]
Eigenvectors 
 [[1.         0.5547002  0.51084069]
 [0.         0.83205029 0.79818857]
 [0.         0.         0.31927543]]


In [5]:
eVe[1]/eVe[1].max()

array([0.        , 1.        , 0.95930327])

# Latihan 1:

* Diberikan matrix sbb: 
$$ \begin{bmatrix}
    -2 & -3 \\
    6 & 7
\end{bmatrix} $$
* Tentukan **Error Relatif** aproksimasi eigenvalue terkait matrix tersebut 
* jika persamaan karakteristik polinomial-nya diselesaikan dengan metode Newton
* **tiga iterasi** ($\lambda_3$) dengan $\lambda_0 = 1$ 

In [6]:
def F(x):
    return x**2-5*x+4
def f(x):
    return 2*x-5
# Newton (L3, Lo=1)
Lo =1
L1 = Lo - F(Lo)/f(Lo)
L2 = L1 - F(L1)/f(L1)
L3 = L2 - F(L2)/f(L2)
L3
eksak = 1
abs(L3-eksak)/abs(eksak) # Error_Relatif

0.0

<p><img alt="" src="images/eigen_Pwr_Method_1.png" /></p>


<p><img alt="" src="images/eigen_Pwr_Method_Alg.png" style="width: 680px; height: 240px;" /></p>


<h1 id="Power-Method---Contoh">Power Method - Contoh</h1>

<p><img alt="" src="images/eigen_Pwr_Method_eg.png" style="width: 800px; height: 528px;" /></p>


<p><img alt="" src="images/eigen_Pwr_Method_inv.png" style="width: 736px; height: 183px;" /></p>


In [7]:
# Contoh
A = np.array([[ 2, 9 ],[ 9, 1 ]])
x = np.array([1,1]).transpose()
N = 5
for i in range(N):
    xo = x
    x = A.dot(x)
    x1 = x
    eigen = max(abs(x1))/max(abs(xo))
print('Eigenvalue = ', eigen)
print('Eigenvector = ', x)

Eigenvalue =  10.63820909893284
Eigenvector =  [132584 124129]


In [8]:
eVa, eVe = np.linalg.eig(A)
print('Eigenvalues \n',eVa)
print('Eigenvectors \n',eVe)

Eigenvalues 
 [10.51387819 -7.51387819]
Eigenvectors 
 [[ 0.72645372 -0.68721539]
 [ 0.68721539  0.72645372]]


In [9]:
# Seringnya Power method menggunakan normalisasi vector di setiap langkahnya
x = np.array([1,1]).transpose()
N = 6
for i in range(N):
    x = x/x.max()
    xo = x
    x = A.dot(x)
    x1 = x
    eigen = max(abs(x1))/max(abs(xo))
print('Eigenvalue = ', eigen)
print('Eigenvector = ', x/x.max())

Eigenvalue =  10.426061968261632
Eigenvector =  [1.         0.95301842]


# Latihan 2:

* Diberikan matrix sbb: 
$$ \begin{bmatrix}
    1 & 1 \\
    4 & 1
\end{bmatrix} $$
* Tentukan **Error Relatif** aproksimasi eigenvalue 
* terkait matrix tersebut jika eigenvalue-nya didekati 
* dengan metode **Rayleigh** power Method **dua iterasi** ($\lambda_2$) dengan $x_0 = [1,1]'$ 

In [10]:
# Contoh
A = np.array([[ 1, 1 ],[ 4, 1 ]])
x = np.array([1,1]).transpose()
N = 4
for i in range(N):
    xo = x
    x = A.dot(x)
    x1 = x
    eigen = max(abs(x1))/max(abs(xo))
print('Eigenvalue = ', eigen)
print('Error Relatif = ', abs(3-eigen)/3)

Eigenvalue =  2.951219512195122
Error Relatif =  0.016260162601626032


<h1 id="Rayleigh-Quotient">Rayleigh Quotient</h1>

<ul>
	<li>Secara umum Power method Lambat, methode Rayleigh mempercepat iterasi Power Method</li>
	<li><img alt="" src="images/eigen_rayleigh_Quotient_1.png" style="width: 609px; height: 296px;" /></li>
</ul>


In [11]:
# Contoh (Sebelumnya)
import numpy as np
A = np.array([[ 1, 0, 2 ],[ 0, 1, 1 ], [2, 1, 2]])
A = np.linalg.inv(A)
x = np.array([1,1, 1]).transpose()
N = 2
eksak = -1
for i in range(N):
    xo = x
    x = A.dot(x)
    x1 = x
    eigen = max(abs(x1))/max(abs(xo))
    eigenRayleigh = x.transpose().dot(A).dot(x)/x.transpose().dot(x)
    
print('EigenValue Menurut metode Rayleigh 2 iterasi =', eigenRayleigh)    
    
print('EA Eigenvalue (Power Method)= ', abs(eigen-eksak))
print('EA Eigenvalue (Rayleigh)= ', abs(eigenRayleigh-eksak))
print('Eigenvector = ', x)

EigenValue Menurut metode Rayleigh 2 iterasi = -0.5555555555555552
EA Eigenvalue (Power Method)=  2.0
EA Eigenvalue (Rayleigh)=  0.44444444444444475
Eigenvector =  [ 0.33333333  0.66666667 -0.33333333]


<h1 id="End-of-Week-13">End of Module</h1>

<hr />
...