<center><img alt="" src="images/Cover_NLPTM.jpg"/></center> 

## <center><font color="blue">Representasi Dokumen</font></center>
<b><center>(C) Taufik Sutanto - 2020</center>
<center>tau-data Indonesia ~ https://tau-data.id ~ taufik@tau-data.id</center>

In [ ]:
# Installing Modules for Google Colab
import nltk

!wget https://raw.githubusercontent.com/taudata-indonesia/eLearning/master/taudataNlpTm.py
!mkdir data
!wget -P data/ https://raw.githubusercontent.com/taudata-indonesia/eLearning/master/data/slang.txt
!wget -P data/ https://raw.githubusercontent.com/taudata-indonesia/eLearning/master/data/stopwords_id.txt
!wget -P data/ https://raw.githubusercontent.com/taudata-indonesia/eLearning/master/data/stopwords_en.txt
!wget -P data/ https://raw.githubusercontent.com/taudata-indonesia/eLearning/master/data/wn-ind-def.tab
!wget -P data/ https://raw.githubusercontent.com/taudata-indonesia/eLearning/master/data/wn-msa-all.tab
!wget -P data/ https://raw.githubusercontent.com/taudata-indonesia/eLearning/master/data/all_indo_man_tag_corpus_model.crf.tagger

!pip install spacy python-crfsuite unidecode textblob sastrawi tweepy twython
!python -m spacy download en
!python -m spacy download xx
!python -m spacy download en_core_web_sm

nltk.download('popular')

In [5]:
import taudataNlpTm as tau, seaborn as sns; sns.set()
import tweepy, json, nltk, urllib.request
from textblob import TextBlob
from nltk.tokenize import TweetTokenizer
from twython import TwythonStreamer  
from tqdm import tqdm_notebook as tqdm

<h1 id="Vector-Space-Model---VSM">Vector Space Model - VSM</h1>

<p><img alt="" src="images/vsm.png" style="width: 300px; height: 213px;" /></p>


## <font color="blue">Outline Representasi Dokumen :</font>
* Representasi Sparse (VSM): Binary, tf &amp;-/ idf, Custom tf-idf, BM25
* Frequency filtering, n-grams, vocabulary based
* Representasi Dense:&nbsp;Word Embedding (Word2Vec dan FastText)
* Tensor to Matrix representation untuk model Machine Learning di Text Mining

<ul>
	<li>Data yang biasanya kita ketahui berbentuk <strong>tabular </strong>(tabel/kolom-baris/matriks/<em>array</em>/larik), data seperti ini disebut data terstruktur (<strong><em>structured data</em></strong>).</li>
	<li>Data terstruktur dapat disimpan dengan baik di&nbsp;<em>spreadsheet</em>&nbsp;(misal:&nbsp;<em>Excel/CSV</em>) atau basis data (<em>database</em>) relasional dan secara umum dapat digunakan langsung oleh berbagai model/<em>tools</em>&nbsp;statistik/data mining konvensional.</li>
	<li>Sebagian data yang lain memiliki &ldquo;<em>tags</em>&rdquo; yang menjelaskan elemen semantik yang berbeda di dalamnya dan cenderung tidak memiliki skema (struktur) yang statis.</li>
	<li>Data seperti ini disebut data<em>&nbsp;<strong>semi-structured</strong></em>, contohnya data dalam bentuk &nbsp;<strong><a href="http://www.w3.org/XML/" target="_blank">XML</a></strong>.</li>
	<li>Apa bedanya? Apa maksudnya tidak memiliki skema yang statis? Penjelasan mudahnya bayangkan sebuah data terstruktur (tabular), namun dalam setiap baris (<em>record/instance</em>)-nya tidak memiliki jumlah variabel (peubah) yang sama.</li>
	<li>Tentu saja data seperti ini tidak sesuai jika disimpan dan diolah dengan&nbsp;<em>tools/software</em>&nbsp;yang mengasumsikan struktur yang statis pada setiap barisnya (misal: Excel dan SPSS).</li>
</ul>

<p><img alt="" src="images/3_tipeData.png" style="height: 400px ; width: 430px" /></p>


<ul>
	<li>Data multimedia seperti teks, gambar atau video <strong>tidak dapat</strong>&nbsp;<strong>secara langsung</strong>&nbsp;dianalisa dengan model statistik/data mining.</li>
	<li>Sebuah proses awal&nbsp;<em>(pre-process)</em>&nbsp;harus dilakukan terlebih dahulu untuk merubah data-data tidak (semi) terstruktur tersebut menjadi bentuk yang dapat digunakan oleh model statistik/data mining konvensional.</li>
	<li>Terdapat berbagai macam cara mengubah data-data tidak terstruktur tersebut ke dalam bentuk yang lebih sederhana, dan ini adalah suatu bidang ilmu tersendiri yang cukup dalam. Sebagai contoh saja sebuah teks biasanya dirubah dalam bentuk vektor/<em>topics</em>&nbsp;terlebih dahulu sebelum diolah.</li>
	<li>Vektor data teks sendiri bermacam-macam jenisnya: ada yang berdasarkan eksistensi (<strong><em>binary</em></strong>), frekuensi dokumen (<strong>tf</strong>), frekuensi dan invers jumlah dokumennya dalam corpus (<strong><a href="https://en.wikipedia.org/wiki/Tf%E2%80%93idf" target="_blank">tf-idf</a></strong>), <strong>tensor</strong>, dan sebagainya.</li>
	<li>&nbsp;Proses perubahan ini sendiri biasanya tidak&nbsp;<em>lossless</em>, artinya terdapat cukup banyak informasi yang hilang. Maksudnya bagaimana? Sebagai contoh ketika teks direpresentasikan dalam vektor (sering disebut sebagai model <strong>bag-of-words</strong>) maka informasi urutan antar kata menghilang.&nbsp;</li>
</ul>

<p><img alt="" src="images/3_structureData.png" style="height:270px; width:578px" /></p>


<p><strong>Contoh bentuk umum representasi dokumen:</strong></p>


<p><img alt="" src="images/3_Bentuk umum representasi dokumen.JPG" style="height: 294px ; width: 620px" /></p>

<p>Pada Model <em>n-grams</em> kolom bisa juga berupa frase.</p>

<h2 id="Document-Term-Matrix-:-Vector-Space-Model---VSM">Document-Term Matrix : Vector Space Model - VSM</h2>

<p><img alt="" src="images/vsm_matrix.png" style="width: 500px; height: 283px;" /></p>


<p><img alt="" src="images/3_rumus tfidf.png" style="height:370px; width:367px" /></p>


<p><img alt="" src="images/3_tfidf logic.jpg" style="height:359px; width:638px" /></p>

<p><img alt="" src="images/3_variant tfidf.png" style="height:334px; width:955px" /></p>
K = |d|

# pertama-tama mari kita Load Data twitter dari pertemuan sebelumnya

* Silahkan gunakan data baru (crawl lagi) jika diinginkan

In [6]:
def loadTweets(file='Tweets.json'):
    f=open(file,encoding='utf-8', errors ='ignore', mode='r')
    T=f.readlines();f.close()
    for i,t in enumerate(T):
        T[i] = json.loads(t.strip())
    return T

In [12]:
# karena ToS data json ini dikirimkan terpisah hanya untuk kalangan terbatas.
import json

T2 = loadTweets(file='data/tweets_sma-01.json')
print('Total data = {}'.format(len(data)))
print('tweet pertama oleh "{}" : "{}"'.format(T2[0]['user']['screen_name'],T2[0]['full_text']))

Total data = 300
tweet pertama oleh "maher68554742" : "RT @TRANSTV_CORP: Masuk kembali ke masa PSBB Transisi, kini traveler bisa kembali melangsungkan pernikahan di hotel. Hanya wajib lapor dulu…"


In [28]:
# Contoh mengambil hanya data tweet
data = [t['full_text'] for t in T2]
data[:5] # 5 tweet pertama

['RT @TRANSTV_CORP: Masuk kembali ke masa PSBB Transisi, kini traveler bisa kembali melangsungkan pernikahan di hotel. Hanya wajib lapor dulu…',
 'RT @TRANSTV_CORP: Masuk kembali ke masa PSBB Transisi, kini traveler bisa kembali melangsungkan pernikahan di hotel. Hanya wajib lapor dulu…',
 'RT @tempodotco: PSBB Transisi, 77 RPTRA di Jakarta Utara Dibuka Lagi #TempoMetro https://t.co/yipPjc3J0D',
 'Pemprov DKI Jakarta akhirnya mengizinkan bioskop buka saat PSBB transisi. Namun, kebijakan ini masih sulit membangkitkan bisnis bioskop yang telah terpuruk selama pandemii Covid-19. #Analisis\nhttps://t.co/WeK7rk2ieU',
 'Hari Ke-9 PSBB Transisi, Jumlah Positif Corona di Jakarta Tambah 964 Kasus https://t.co/olB2lkHhTb #DariSuara']

# PreProcessing Data Text-nya

In [34]:
# pre processing
import taudataNlpTm as tau 
from tqdm import tqdm_notebook as tqdm

# cleanText(T, fix={}, lemma=None, stops = set(), symbols_remove = True, min_charLen = 2, fixTag= True)
stops, lemmatizer = tau.LoadStopWords(lang='id')
stops.add('rt')
stops.add('..')
for i,d in tqdm(enumerate(data)):
    data[i] = tau.cleanText(d, lemma=lemmatizer, stops = stops, symbols_remove = True, min_charLen = 2)
print(data[0])


transtv_corp masuk psbb transisi traveler melangsungkan pernikahan hotel wajib lapor


In [30]:
# Menggunakan modul SciKit untuk merubah data tidak terstruktur ke VSM
# Scikit implementation http://scikit-learn.org/stable/modules/feature_extraction.html

from sklearn.feature_extraction.text import TfidfVectorizer, CountVectorizer

# http://scikit-learn.org/stable/modules/generated/sklearn.feature_extraction.text.CountVectorizer.html#sklearn.feature_extraction.text.CountVectorizer
# http://scikit-learn.org/stable/modules/generated/sklearn.feature_extraction.text.TfidfVectorizer.html#sklearn.feature_extraction.text.TfidfVectorizer

In [35]:
# VSM - "binari"
binary_vectorizer = CountVectorizer(binary = True)
binari = binary_vectorizer.fit_transform(data)
binari.shape # ukuran VSM

(300, 614)

In [14]:
# Sparse vectors/matrix
binari[0]

<1x820 sparse matrix of type '<class 'numpy.int64'>'
	with 19 stored elements in Compressed Sparse Row format>

In [15]:
# Mengakses Datanya
print(binari[0].data)
print(binari[0].indices)

[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
[627 766 437 353 335 433 595 765 372 767 129 443 576 176 261 252 793 397
 214]


In [16]:
# Kolom dan term
print(str(binary_vectorizer.vocabulary_)[:93])

{'rt': 627, 'transtv_corp': 766, 'masuk': 437, 'kembali': 353, 'ke': 335, 'masa': 433, 'psbb'


In [36]:
# VSM term Frekuensi : "tf"
tf_vectorizer = CountVectorizer(binary = False)
tf = tf_vectorizer.fit_transform(data)

print(tf.shape) # Sama
print(tf[0].data) # Hanya data ini yg berubah
print(tf[0].indices) # Letak kolomnya tetap sama

(300, 614)
[1 1 1 1 1 1 1 1 1 1]
[576 328 457 575 577 330 440 199 597 296]


In [18]:
d = tf_vectorizer.vocabulary_
kata_kolom = {k:v for v,k in d.items()}
kata_kolom[99]

'benhil'

In [37]:
# VSM term Frekuensi : "tf-idf"
tfidf_vectorizer = TfidfVectorizer()
tfidf = tfidf_vectorizer.fit_transform(data)

print(tfidf.shape) # Sama
print(tfidf[0].data) # Hanya data ini yg berubah
print(tfidf[0].indices) # Letak kolomnya berbeda, namun jumlah kolom dan elemennya tetap sama

(300, 614)
[0.34054588 0.32748541 0.33604046 0.33827305 0.33827305 0.33827305
 0.27160567 0.14364223 0.3295704  0.34286042]
[296 597 199 440 330 577 575 457 328 576]


## Custom tf-idf:
* Menurut http://scikit-learn.org/stable/modules/generated/sklearn.feature_extraction.text.TfidfVectorizer.html
* default formula tf-idf yang digunakan sk-learn adalah:
* $tfidf = tf * log(\frac{N}{df+1})$ ==> Smooth IDF
* namun kita merubahnya menjadi:
* $tfidf = tf * log(\frac{N}{df})$ ==> Non Smooth IDF
* $tfidf = tf * log(\frac{N}{df+1})$ ==> linear_tf, Smooth IDF
* $tfidf = (1+log(tf)) * log(\frac{N}{df})$ ==> sublinear_tf, Non Smooth IDF

In [20]:
# VSM term Frekuensi : "tf-idf"
tfidf_vectorizer = TfidfVectorizer(smooth_idf= False, sublinear_tf=True)
tfidf = tfidf_vectorizer.fit_transform(data)
print(tfidf.shape) # Sama
print(tfidf[0].data) # Hanya data ini yg berubah
print(tfidf[0].indices) # Letak kolomnya = tfidf

(300, 820)
[0.24182422 0.24182422 0.23243909 0.20570688 0.23858472 0.15261888
 0.24018974 0.24018974 0.20681344 0.24018974 0.24018974 0.19244826
 0.10148126 0.21138245 0.23096672 0.40128961 0.23393621 0.24348924
 0.11197294]
[214 397 793 252 261 176 576 443 129 767 372 765 595 433 335 353 437 766
 627]


### Alasan melakukan filtering berdasarkan frekuensi:
* Intuitively filter noise 
* Curse of Dimensionality (akan dibahas kemudian)
* Computational Complexity
* Improving accuracy

In [38]:
# Frequency Filtering di VSM
tfidf_vectorizer = TfidfVectorizer()
tfidf_1 = tfidf_vectorizer.fit_transform(data)

tfidf_vectorizer = TfidfVectorizer(max_df=0.75, min_df=5)
tfidf_2 = tfidf_vectorizer.fit_transform(data)

print(tfidf_1.shape)
print(tfidf_2.shape)

(300, 614)
(300, 107)


In [39]:
tfidf_vectorizer = TfidfVectorizer(lowercase=True, smooth_idf= True, sublinear_tf=True, 
                                   ngram_range=(1, 2), max_df=0.90, min_df=2)

tfidf_3 = tfidf_vectorizer.fit_transform(data)
print(tfidf_3.shape)

(300, 469)


<h2 id="Best-Match-Formula-:-BM25">Best-Match Formula : BM25</h2>

<p><img alt="" src="images/3_bm25_simple.png" style="height: 123px; width: 300px;" /></p>

<ol>
	<li>di IR nilai b dan k yang optimal adalah :&nbsp;<strong> <em>b</em> = 0.75&nbsp; dan k = [1.2 - 2.0]&nbsp; &nbsp;</strong><br />
	ref:&nbsp;<em>Christopher, D. M., Prabhakar, R., &amp; Hinrich, S. C. H. &Uuml;. T. Z. E. (2008). Introduction to information retrieval.&nbsp;An Introduction To Information Retrieval,&nbsp;151, 177.</em></li>
	<li>Tapi kalau untuk TextMining (clustering) nilai <strong>k optimal adalah 20, nilai b = sembarang (boleh = 0.75)</strong><br />
	ref:&nbsp;<em>Whissell, J. S., &amp; Clarke, C. L. (2011). Improving document clustering using Okapi BM25 feature weighting.&nbsp;Information retrieval,&nbsp;14(5), 466-487.</em></li>
	<li><strong>avgDL </strong>adalah rata-rata panjang dokumen di seluruh dataset dan <strong>DL </strong>adalah panjang dokumen D.<br />
	hati-hati, ini berbeda dengan &nbsp;tf-idf MySQL diatas.</li>
</ol>


In [22]:
# Variasi pembentukan matriks VSM:
d1 = '@udin76, Minum kopi pagi-pagi sambil makan pisang goreng is the best'
d2 = 'Belajar NLP dan Text Mining ternyata seru banget sadiezz'
d3 =  'Sudah lumayan lama bingits tukang Bakso belum lewat'
d4 = 'Aduh ga banget makan Mie Ayam p4k4i kesyap, please deh'

D = [d1, d2, d3, d4]
# Jika kita menggunakan cara biasa: 
tfidf_vectorizer = TfidfVectorizer()
vsm = tfidf_vectorizer.fit_transform(D)
print(tfidf_vectorizer.vocabulary_)

{'udin76': 35, 'minum': 21, 'kopi': 14, 'pagi': 24, 'sambil': 28, 'makan': 18, 'pisang': 25, 'goreng': 11, 'is': 12, 'the': 33, 'best': 6, 'belajar': 4, 'nlp': 22, 'dan': 8, 'text': 32, 'mining': 20, 'ternyata': 31, 'seru': 29, 'banget': 3, 'sadiezz': 27, 'sudah': 30, 'lumayan': 17, 'lama': 15, 'bingits': 7, 'tukang': 34, 'bakso': 2, 'belum': 5, 'lewat': 16, 'aduh': 0, 'ga': 10, 'mie': 19, 'ayam': 1, 'p4k4i': 23, 'kesyap': 13, 'please': 26, 'deh': 9}


In [23]:
# N-Grams VSM
# Bermanfaat untuk menangkap frase kata, misal: "ga banget", "pisang goreng", dsb
tfidf_vectorizer = TfidfVectorizer(ngram_range=(1, 2))
vsm = tfidf_vectorizer.fit_transform(D)
print(tfidf_vectorizer.vocabulary_)

{'udin76': 69, 'minum': 41, 'kopi': 27, 'pagi': 47, 'sambil': 55, 'makan': 34, 'pisang': 50, 'goreng': 21, 'is': 23, 'the': 65, 'best': 13, 'udin76 minum': 70, 'minum kopi': 42, 'kopi pagi': 28, 'pagi pagi': 48, 'pagi sambil': 49, 'sambil makan': 56, 'makan pisang': 36, 'pisang goreng': 51, 'goreng is': 22, 'is the': 24, 'the best': 66, 'belajar': 9, 'nlp': 43, 'dan': 16, 'text': 63, 'mining': 39, 'ternyata': 61, 'seru': 57, 'banget': 6, 'sadiezz': 54, 'belajar nlp': 10, 'nlp dan': 44, 'dan text': 17, 'text mining': 64, 'mining ternyata': 40, 'ternyata seru': 62, 'seru banget': 58, 'banget sadiezz': 8, 'sudah': 59, 'lumayan': 32, 'lama': 29, 'bingits': 14, 'tukang': 67, 'bakso': 4, 'belum': 11, 'lewat': 31, 'sudah lumayan': 60, 'lumayan lama': 33, 'lama bingits': 30, 'bingits tukang': 15, 'tukang bakso': 68, 'bakso belum': 5, 'belum lewat': 12, 'aduh': 0, 'ga': 19, 'mie': 37, 'ayam': 2, 'p4k4i': 45, 'kesyap': 25, 'please': 52, 'deh': 18, 'aduh ga': 1, 'ga banget': 20, 'banget makan': 7

In [24]:
# Vocabulary based VSM
# Bermanfaat untuk menghasilkan hasil analisa yang "bersih"
# variasi 2
d1 = '@udin76, Minum kopi pagi-pagi sambil makan pisang goreng is the best'
d2 = 'Belajar NLP dan Text Mining ternyata seru banget sadiezz'
d3 =  'Sudah lumayan lama bingits tukang Bakso belum lewat seru'
d4 = 'Aduh ga banget makan Mie Ayam p4k4i kesyap, please deh'
D = [d1,d2,d3,d4]
Vocab = {'seru banget':0, 'seru':1, 'the best':2, 'lama':3, 'text mining':4, 'nlp':5, 'ayam':6}
tf_vectorizer = CountVectorizer(binary = False, vocabulary=Vocab)
tf = tf_vectorizer.fit_transform(D)
print(tf.toarray())
tf_vectorizer.vocabulary_

[[0 0 0 0 0 0 0]
 [0 1 0 0 0 1 0]
 [0 1 0 1 0 0 0]
 [0 0 0 0 0 0 1]]


{'seru banget': 0,
 'seru': 1,
 'the best': 2,
 'lama': 3,
 'text mining': 4,
 'nlp': 5,
 'ayam': 6}

In [25]:
Vocab = {'seru banget':0, 'the best':1, 'lama':2, 'text mining':3, 'nlp':4, 'ayam':5}
tfidf_vectorizer = TfidfVectorizer(max_df=1.0, min_df=1, lowercase=True, vocabulary=Vocab)
vsm = tfidf_vectorizer.fit_transform(D)
print(tfidf_vectorizer.vocabulary_)
# VSM terurut sesuai definisi dan terkesan lebih "bersih"
# Perusahaan besar biasanya memiliki menggunakan teknik ini dengan vocabulary yang comprehensif
# Sangat cocok untuk Sentiment Analysis

{'seru banget': 0, 'the best': 1, 'lama': 2, 'text mining': 3, 'nlp': 4, 'ayam': 5}


<h2><strong>Word Embeddings</strong></h2>

<h2><img alt="" src="images/3_word_embeddings.png" style="height: 296px ; width: 602px" /></h2>

<p><img alt="" src="images/3_word2vec_example.png" style="height:400px; width:667px" /></p>


<h3>Word2Vec</h3>

<p><img alt="" src="images/3_word2Vec.png" style="height:400px; width:636px" /><br />
Dikembangkan oleh Tomas Mikolov - Google :</p>

<p>Goldberg, Yoav; Levy, Omer. &quot;word2vec Explained: Deriving Mikolov et al.&#39;s Negative-Sampling Word-Embedding Method&quot;.&nbsp;<a href="https://en.wikipedia.org/wiki/ArXiv">arXiv</a>:<a href="https://arxiv.org/abs/1402.3722">1402.3722</a> </p>


<p><img alt="" src="images/BoW_VS_WordEmbedding.png" style="width: 248px; height: 372px;" /></p>


In [40]:
data[:3]

['transtv_corp masuk psbb transisi traveler melangsungkan pernikahan hotel wajib lapor',
 'transtv_corp masuk psbb transisi traveler melangsungkan pernikahan hotel wajib lapor',
 'tempodotco psbb transisi 77 rptra jakarta utara dibuka tempo metro']

In [41]:
# Rubah bentuk data seperti yang dibutuhkan genSim
# Bisa juga dilakukan dengan memodifikasi fungsi "cleanText" (agar lebih efisien)

data_we = []
for doc in data:
    Tokens = [str(w) for w in TextBlob(doc).words]
    data_we.append(Tokens)
print(data_we[:3])

[['transtv_corp', 'masuk', 'psbb', 'transisi', 'traveler', 'melangsungkan', 'pernikahan', 'hotel', 'wajib', 'lapor'], ['transtv_corp', 'masuk', 'psbb', 'transisi', 'traveler', 'melangsungkan', 'pernikahan', 'hotel', 'wajib', 'lapor'], ['tempodotco', 'psbb', 'transisi', '77', 'rptra', 'jakarta', 'utara', 'dibuka', 'tempo', 'metro']]


In [50]:
# https://radimrehurek.com/gensim/models/word2vec.html
# train word2vec dengan data di atas
from gensim.models import Word2Vec

L = 300 # Jumlah neurons = ukuran vektor = jumlah kolom
model_wv = Word2Vec(data_we, min_count=2, size=L, window = 5, workers= -2)
# min_count adalah jumlah kata minimal yang muncul di corpus
# "size" adalah Dimensionality of the word vectors 
# (menurut beberapa literature untuk text disarankan 300-500)
# "window" adalah jarak maximum urutan kata yang di pertimbangkan
# workers = jumlah prosesor yang digunakan untuk menjalankan word2vec
print('Done!...')

Done!...


In [51]:
# di data yang sebenarnya (i.e. besar) Gensim sering membutuhkan waktu cukup lama
# Untungnya kita bisa menyimpan dan me-load kembali hasil perhitungan model word2vec, misal
model_wv.save('data/model_w2v')
model_wv = Word2Vec.load('data/model_w2v')
print('Done!...')

Done!...


### Hati-hati, Word2vec menggunakan Matriks Dense

<p>Penggunaan memory oleh Gensim kurang lebih sebagai berikut:</p>

<p>Jumlah kata x &quot;size&quot; x 12 bytes</p>

<p>Misal terdapat 100 000 kata unik dan menggunakan 200 layers, maka penggunaan memory =&nbsp;</p>

<p>100,000x200x12 bytes = ~229MB</p>

<p>Jika jumlah size semakin banyak, maka jumlah training data yang diperlukan juga semakin banyak, namun model akan semakin akurat.</p>


In [52]:
# Melihat vector suatu kata
vektor = model_wv.wv.__getitem__(['psbb'])
print(len(vektor[0])) # Panjang vektor keseluruhan = jumlah neuron yang digunakan
print(vektor[0][:5]) # 5 elemen pertama dari vektornya

300
[ 1.3707536e-03 -9.4042778e-05  3.2752458e-04  1.3641898e-03
  1.1304108e-04]


In [45]:
# Mencari kata terdekat menurut data training dan Word2Vec
model_wv.wv.most_similar('psbb')

[('menjalankan', 0.15901216864585876),
 ('memberlakukan', 0.13615277409553528),
 ('tingkat', 0.12480050325393677),
 ('10', 0.11427606642246246),
 ('seminggu', 0.10847358405590057),
 ('ayat', 0.10166313499212265),
 ('diizinkan', 0.09671982377767563),
 ('besok', 0.09351169317960739),
 ('selasa', 0.09345486015081406),
 ('bioskop', 0.08977720141410828)]

In [53]:
# Melihat similarity antar kata
print(model_wv.wv.similarity('psbb', 'corona'))
print(model_wv.wv.similarity('psbb', 'jakarta'))
print(model_wv.wv.similarity('psbb', 'psbb'))

0.023337541
-0.11861667
1.0


<p><img alt="" src="images/3_cosine.png" style="height:400px; width:683px" /></p>


## Hati-hati Cosine adalah similarity bukan distance
Hal ini akan mempengaruhi interpretasi

In [55]:
# error jika kata tidak ada di training data
# beckman bukan beckmans ==> hence di Word Embedding PreProcessing harus thourough

kata = 'copid'
try:
    print(model_wv.wv.most_similar(kata))
except:
    print('error! kata "',kata,'" tidak ada di training data')
# ini salah satu kelemahan Word2Vec

error! kata " copid " tidak ada di training data


## Tips:

<p>Hati-hati GenSim tidak menggunakan seluruh kata di training data!.</p>

<p>Perintah berikut akan menghasilkan kata-kata yang terdapat di vocabulary GenSim</p>


In [57]:
Vocabulary = model_wv.wv.vocab
print(str(Vocabulary.keys())[:250])
# Gunakan vocabulary ini (rubah ke "set") untuk membuat program menjadi lebih robust

dict_keys(['transtv_corp', 'masuk', 'psbb', 'transisi', 'traveler', 'melangsungkan', 'pernikahan', 'hotel', 'wajib', 'lapor', 'tempodotco', '77', 'rptra', 'jakarta', 'utara', 'dibuka', 'tempo', 'metro', 'pemprov', 'dki', 'mengizinkan', 'bioskop', 'bu


## Hati-hati menginterpretasikan hasil Word2Vec

<h3 id=" FastText-(Facebook-2016)">&nbsp;FastText (Facebook-2016)</h3>

<ul>
	<li>Menggunakan Sub-words: app, ppl, ple - apple</li>
	<li>Paper:&nbsp;https://arxiv.org/abs/1607.04606&nbsp;&nbsp;</li>
	<li>Website:&nbsp;https://fasttext.cc/</li>
	<li>Source:&nbsp;https://github.com/facebookresearch/fastText&nbsp;</li>
</ul>


In [58]:
# Caution penggunaan memory besar, bila timbul "Memory Error" kecilkan nilai L
from gensim.models import FastText

L = 100 # Jumlah neurons = ukuran vektor = jumlah kolom
model_FT = FastText(data_we, size=L, window=5, min_count=2, workers=-2)
'Done'

'Done'

In [59]:
# Mencari kata terdekat menurut data training dan Word2Vec
model_FT.wv.most_similar('psbb')

[('psbbjakarta', 0.39620503783226013),
 ('psbbtransisi', 0.3755951523780823),
 ('pemprov', 0.25807705521583557),
 ('ya', 0.2563023567199707),
 ('12', 0.22505980730056763),
 ('pengunjung', 0.22196458280086517),
 ('positive', 0.21561191976070404),
 ('19', 0.2093917727470398),
 ('biar', 0.2086964249610901),
 ('dkijakarta', 0.20685012638568878)]

In [60]:
# Melihat similarity antar kata
print(model_FT.wv.similarity('psbb', 'corona'))
print(model_FT.wv.similarity('psbb', 'jakarta'))
print(model_FT.wv.similarity('psbb', 'psbb'))

0.0015008051
0.07263649
1.0


In [61]:
# Word2Vec VS FastText
try:
    print(model_wv.wv.most_similar('coro'))
except:
    print('Word2Vec error!')
    
try:
    print(model_FT.wv.most_similar('coro'))
except:
    print('FastText error!')

Word2Vec error!
[('corona', 0.42177480459213257), ('maju', 0.2425994575023651), ('berpendapat', 0.23979200422763824), ('selasa', 0.22723904252052307), ('kendaraan', 0.21705520153045654), ('udara', 0.21434135735034943), ('udah', 0.21017128229141235), ('melangsungkan', 0.20929008722305298), ('bisnis', 0.2072659730911255), ('cibubur', 0.19852080941200256)]


# Diskusi:
<ul>
	<li>Apakah kelebihan dan kekurangan WE secara umum?</li>
	<li>Apakah kira-kira aplikasi WE?</li>
	<li>Apakah bisa dijadikan representasi dokumen? Bagaimana caranya?</li>
	<li>Bergantung pada apa sajakah performa model WE?</li>
</ul>

* Preprocessing apa yang sebaiknya dilakukan pada model Word Embedding?
* Apakah Pos Tag bermanfaat disini? Jika iya bagaimana menggunakannya?

<h1>End of Module UDA-06</h1>
<hr />
<p><img alt="" src="images/2_Studying_Linguistic.png" style="height:500px; width:667px" /></p>
